
INSERT INTO public.pe_sector_intelligence (sector, subsector, vertical, pe_thesis, multiples_valuations, consolidation_phase, geography, tags)
VALUES
('SALUD', 'DENTAL (DSOs)', 'Odontología general', 'Consolidación DSOs; administración centralizada', '9-12x EBITDA', 'MEDIO CICLO', 'EE.UU.', ARRAY['dental','DSO']),
('SALUD', 'DERMATOLOGÍA', 'Multi-centro', 'Alto margen estético + médico', '8-12x EBITDA', 'MEDIO CICLO', 'EE.UU.', ARRAY['dermatología']),
('SALUD', 'OFTALMOLOGÍA', 'Clínicas', 'Cataratas, LASIK, retina, ASC', '8-11x EBITDA', 'MEDIO CICLO', 'EE.UU.', ARRAY['oftalmología']),
('SALUD', 'SALUD MENTAL', 'Adicciones + ABA', 'Demanda post-COVID explosiva', '7-12x EBITDA', 'TEMPRANO-MEDIO', 'EE.UU.', ARRAY['salud mental']),
('SALUD', 'GASTROENTEROLOGÍA', 'Clínicas GI + ASC', 'Colonoscopias alto margen', '10-14x EBITDA', 'TEMPRANO', 'EE.UU.', ARRAY['gastroenterología']),
('SALUD', 'VETERINARIO', 'Clínicas vet', 'Humanización mascotas', '10-14x EBITDA plataformas', 'MEDIO-AVANZADO', 'EE.UU. + Europa', ARRAY['veterinario']),
('SALUD', 'TECNOLOGÍA SANITARIA', 'RCM / SaaS', 'Software misión crítica proveedores', '15-25x ARR', 'MADURO', 'Global', ARRAY['healthtech','SaaS']),
('CONSTRUCCIÓN', 'CLIMATIZACIÓN (HVAC)', 'Residencial + Comercial', 'Servicio esencial, recurrente tipo SaaS. 480.000 vacantes. Mercado $650.000M.', '7-11x EBITDA', 'MEDIO CICLO', 'EE.UU.', ARRAY['HVAC','servicios de campo']),
('CONSTRUCCIÓN', 'CUBIERTAS / TEJADOS', 'Residencial + Comercial', 'Mercado $23.350M, +229% plataformas en 24 meses. Como HVAC en 2017-18.', '6-9x EBITDA', 'MUY TEMPRANO', 'EE.UU.', ARRAY['cubiertas','tejados']),
('CONSTRUCCIÓN', 'ELECTRICIDAD', 'Centros de datos + Comercial', 'Demanda masiva centros de datos. Gasto federal $1,2 billones.', '7-10x EBITDA', 'TEMPRANO', 'EE.UU.', ARRAY['electricidad']),
('CONSTRUCCIÓN', 'CONTROL DE PLAGAS', 'Residencial + Comercial', 'Suscripción mensual recurrente. Predecible.', '8-12x EBITDA', 'MEDIO CICLO', 'EE.UU. + Europa', ARRAY['plagas','suscripción']),
('CONSTRUCCIÓN', 'PROTECCIÓN INCENDIOS', 'Inspección + Instalación', 'Cumplimiento normativo obligatorio. Como HVAC hace 10 años.', '7-10x EBITDA', 'MUY TEMPRANO', 'EE.UU.', ARRAY['incendios']),
('CONSTRUCCIÓN', 'FONTANERÍA', 'Residencial + Comercial', 'No discrecional. Urgencia = pricing power. Infraestructura envejecida.', '6-9x EBITDA', 'TEMPRANO-MEDIO', 'EE.UU.', ARRAY['fontanería']),
('CONSTRUCCIÓN', 'LAVADO DE COCHES', 'Lavado exprés', 'Suscripción recurrente. Inmobiliario + servicios.', '10-14x EBITDA escala', 'EN AUGE', 'EE.UU.', ARRAY['lavado coches','suscripción']),
('TECNOLOGÍA', 'SaaS VERTICAL', 'Legal + Salud + Finanzas', 'Software misión crítica, altos costes cambio. Suscripción recurrente.', '10-25x ARR', 'MUY FUERTE', 'Global', ARRAY['SaaS','vertical']),
('TECNOLOGÍA', 'CIBERSEGURIDAD', 'Endpoint / Red', 'Cumplimiento normativo + IA aumenta amenazas y defensa.', '15-25x ARR', 'FUERTE', 'EE.UU. + Europa + Israel', ARRAY['ciberseguridad']),
('TECNOLOGÍA', 'CENTROS DE DATOS', 'Colocation + Hiperescala', 'Explosión demanda IA. 88% GPs = sector más prometedor 2026.', 'Cap rates 4-6%. Valor por MW.', 'EXPLOSIVO', 'Global', ARRAY['centros de datos','IA']),
('TECNOLOGÍA', 'INTELIGENCIA ARTIFICIAL', 'Infraestructura + Aplicada', 'Computación, entrenamiento, inferencia. IA empresarial vertical.', '20-50x ARR alto crecimiento', 'EXPLOSIVO', 'EE.UU. + Global', ARRAY['IA']),
('TECNOLOGÍA', 'FINTECH', 'Pagos', 'Ingresos transaccionales. Efectos de red. Mega-operaciones.', '15-25x EBITDA', 'FUERTE', 'Global', ARRAY['fintech','pagos']),
('TECNOLOGÍA', 'MSP / SERVICIOS TI', 'Consolidación MSP', 'Mercado PYME fragmentado. Contratos recurrentes.', '12-15x EBITDA plataformas', 'ACTIVO', 'EE.UU. + Europa', ARRAY['MSP','TI']),
('SERVICIOS PROFESIONALES', 'AUDITORÍA / CONTABILIDAD', 'Firmas CPA', 'PE compró 11 de 30 mayores EE.UU. Crisis sucesión. EisnerAmper ~$2.000M.', '12-18x EBITDA', 'BOOM', 'EE.UU. + UK', ARRAY['auditoría','CPA']),
('SERVICIOS PROFESIONALES', 'GESTIÓN PATRIMONIAL', 'RIAs', 'Comisiones recurrentes sobre AUM. Focus Financial $7.000M.', '15-20x EBITDA plataformas', 'MEDIO CICLO', 'EE.UU.', ARRAY['wealth management']),
('SERVICIOS PROFESIONALES', 'SEGUROS', 'MGAs / Corredurías', 'Arbitraje adquisición. Acrisure $20.000M+ ingresos.', '12-16x EBITDA plataformas', 'MEDIO-AVANZADO', 'EE.UU. + UK', ARRAY['seguros']),
('SERVICIOS PROFESIONALES', 'INSPECCIÓN Y CERTIFICACIÓN', 'TIC', 'Regulación, recurrente, esencial. Applus+ (España).', '12-16x EBITDA', 'MEDIO', 'Europa + Global', ARRAY['TIC','España']),
('SERVICIOS PROFESIONALES', 'CONSULTORÍA', 'Gestión + Tecnológica', 'Especializada = prima. GRC, sostenibilidad, IA.', '8-14x EBITDA', 'TEMPRANO-MEDIO', 'Europa + EE.UU.', ARRAY['consultoría']),
('SERVICIOS PROFESIONALES', 'SERVICIOS JURÍDICOS', 'Despachos UK (ABS)', 'Desregulación UK permite propiedad PE.', '8-12x EBITDA', 'TEMPRANO', 'UK', ARRAY['legal','ABS']),
('SERVICIOS PROFESIONALES', 'EDUCACIÓN', 'Colegios privados', 'Nord Anglia $14.500M = mayor operación PE europea 2024.', '12-16x EBITDA', 'SELECTIVO', 'Global', ARRAY['educación']),
('INDUSTRIALES', 'QUÍMICAS', 'Especialidades + Recubrimientos', 'PI, barreras entrada. Escisiones DACH x4 en 2024.', '8-13x EBITDA', 'FUERTE', 'Europa + EE.UU.', ARRAY['químicas']),
('INDUSTRIALES', 'AEROESPACIAL Y DEFENSA', 'Componentes / Posventa', 'Gasto geopolítico. TransDigm >50% márgenes.', '12-16x EBITDA', 'CRECIENTE', 'EE.UU. + Europa', ARRAY['defensa']),
('INDUSTRIALES', 'AGUA Y MEDIO AMBIENTE', 'Filtración / Tecnología agua', 'Regulación PFAS. Escasez. ESG.', '12-18x EBITDA', 'CRECIENTE', 'Global', ARRAY['agua','ESG']),
('INDUSTRIALES', 'DISTRIBUCIÓN', 'Industrial', 'Fragmentada, esencial. Mejora operacional.', '7-10x EBITDA', 'ESTABLE', 'EE.UU. + Europa', ARRAY['distribución']),
('CONSUMO', 'BELLEZA Y BIENESTAR', 'VMS + Cosmética', 'Tendencia premium. DTC + retail. Marcas limpia.', '10-18x EBITDA', 'FUERTE', 'Global', ARRAY['belleza','VMS']),
('CONSUMO', 'MASCOTAS', 'Alimentación + Vet + Retail', 'Humanización. >$150.000M gasto anual EE.UU.', '10-14x EBITDA', 'FUERTE', 'EE.UU. + Europa', ARRAY['mascotas']),
('CONSUMO', 'AGROALIMENTACIÓN', 'España/Iberia foco PE', 'Cítricos, frutos rojos, ecológico. Roland Berger: Iberia = alta convicción.', '7-10x EBITDA', 'CRECIENTE', 'España + Europa', ARRAY['agroalimentación','España']),
('CONSUMO', 'QSR / RESTAURACIÓN', 'Franquicias', 'Modelo ligero activos. Subway $9.600M (Roark).', '10-14x EBITDA franquiciadores', 'ESTABLE', 'EE.UU. + Global', ARRAY['QSR','franquicias']),
('CONSUMO', 'SERVICIOS FUNERARIOS', 'Funerarias + Cementerios', 'A prueba de recesión. 19.000 funerarias fragmentadas.', '8-11x EBITDA', 'ESTABLE', 'EE.UU.', ARRAY['funerarios']),
('ENERGÍA', 'RENOVABLES', 'Solar + Eólica', 'UE mayor mercado ESG. Solar = mayor fuente electricidad UE.', 'TIR 8-12%', 'FUERTE', 'Europa + Global', ARRAY['renovables','ESG']),
('ENERGÍA', 'NUCLEAR', 'SMR / Modular', 'Demanda IA carga base. Net-zero.', 'Fase temprana', 'EMERGENTE', 'EE.UU. + Europa', ARRAY['nuclear','SMR']),
('ENERGÍA', 'RED ELÉCTRICA', 'Transmisión + Distribución', 'Redes envejecidas. Centros datos. Carga VE.', 'Rentabilidades reguladas + prima', 'FUERTE', 'Europa + EE.UU.', ARRAY['red eléctrica']),
('ENERGÍA', 'RESIDUOS / CIRCULAR', 'Gestión residuos + Reciclaje', 'Monopolios locales, densidad rutas.', '10-14x EBITDA', 'CRECIMIENTO ESTABLE', 'EE.UU. + Europa', ARRAY['residuos','circular']),
-- Revocar permisos anon insert tras seed
('INDUSTRIALES', 'ENVASES', 'Flexibles y rígidos', 'Esencial, defensivo. Alimentación y farma. Sostenibilidad.', '8-11x EBITDA', 'ESTABLE', 'Global', ARRAY['envases']),
('INDUSTRIALES', 'MATERIALES CONSTRUCCIÓN', 'Materiales + Componentes', 'Ciclo inmobiliario + renovación. Eficiencia energética.', '8-12x EBITDA', 'CRECIENTE', 'EE.UU. + Europa', ARRAY['materiales','construcción']),
('INDUSTRIALES', 'AUTOMOCIÓN', 'Recambios posventa', 'No discrecional. Flota 12,5 años. Transición VE.', '7-10x EBITDA', 'TRANSICIÓN', 'Global', ARRAY['automoción','VE']);

-- Revocar permisos de insert anon tras seed
REVOKE INSERT ON public.pe_sector_intelligence FROM anon;
