-- Add AI classification fields to contact_leads table
ALTER TABLE public.contact_leads
ADD COLUMN IF NOT EXISTS ai_sector_pe TEXT,
ADD COLUMN IF NOT EXISTS ai_sector_name TEXT,
ADD COLUMN IF NOT EXISTS ai_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_business_model_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_negative_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_classification_confidence INTEGER,
ADD COLUMN IF NOT EXISTS ai_classification_at TIMESTAMP WITH TIME ZONE;

-- Add same fields to company_valuations (most common lead type)
ALTER TABLE public.company_valuations
ADD COLUMN IF NOT EXISTS ai_sector_pe TEXT,
ADD COLUMN IF NOT EXISTS ai_sector_name TEXT,
ADD COLUMN IF NOT EXISTS ai_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_business_model_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_negative_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_classification_confidence INTEGER,
ADD COLUMN IF NOT EXISTS ai_classification_at TIMESTAMP WITH TIME ZONE;

-- Add same fields to acquisition_leads
ALTER TABLE public.acquisition_leads
ADD COLUMN IF NOT EXISTS ai_company_summary TEXT,
ADD COLUMN IF NOT EXISTS ai_company_summary_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS ai_sector_pe TEXT,
ADD COLUMN IF NOT EXISTS ai_sector_name TEXT,
ADD COLUMN IF NOT EXISTS ai_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_business_model_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_negative_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_classification_confidence INTEGER,
ADD COLUMN IF NOT EXISTS ai_classification_at TIMESTAMP WITH TIME ZONE;

-- Add same fields to general_contact_leads
ALTER TABLE public.general_contact_leads
ADD COLUMN IF NOT EXISTS ai_company_summary TEXT,
ADD COLUMN IF NOT EXISTS ai_company_summary_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS ai_sector_pe TEXT,
ADD COLUMN IF NOT EXISTS ai_sector_name TEXT,
ADD COLUMN IF NOT EXISTS ai_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_business_model_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_negative_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_classification_confidence INTEGER,
ADD COLUMN IF NOT EXISTS ai_classification_at TIMESTAMP WITH TIME ZONE;

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_contact_leads_ai_sector ON public.contact_leads(ai_sector_pe);
CREATE INDEX IF NOT EXISTS idx_company_valuations_ai_sector ON public.company_valuations(ai_sector_pe);
CREATE INDEX IF NOT EXISTS idx_acquisition_leads_ai_sector ON public.acquisition_leads(ai_sector_pe);

-- Comment on columns for documentation
COMMENT ON COLUMN public.contact_leads.ai_sector_pe IS 'PE sector classification key (e.g., healthcare, technology)';
COMMENT ON COLUMN public.contact_leads.ai_sector_name IS 'Human readable sector name in Spanish';
COMMENT ON COLUMN public.contact_leads.ai_tags IS 'Array of classification tags generated by AI';
COMMENT ON COLUMN public.contact_leads.ai_business_model_tags IS 'Array of business model tags (e.g., recurring_revenue, capex_light)';
COMMENT ON COLUMN public.contact_leads.ai_negative_tags IS 'Array of negative/exclusion tags';
COMMENT ON COLUMN public.contact_leads.ai_classification_confidence IS 'AI confidence score 0-100';
COMMENT ON COLUMN public.contact_leads.ai_classification_at IS 'Timestamp when AI classification was performed';