-- Insertar noticia de capital riesgo español con operaciones 2025
INSERT INTO public.news_articles (
  title,
  slug,
  excerpt,
  content,
  category,
  tags,
  source_name,
  source_url,
  published_at,
  is_published,
  is_processed,
  deal_type,
  buyer,
  seller,
  target_company,
  deal_value,
  relevance_score,
  ai_metadata,
  read_time,
  author_name
) VALUES (
  'El capital riesgo español acelera con ventas por más de 5.000 millones en 2025',
  'capital-riesgo-espanol-ventas-5000-millones-2025',
  'Las principales gestoras españolas (Portobello, MCH, GPF, ProA) completan más de 20 desinversiones en 2025 para devolver capital a inversores y levantar nuevos fondos.',
  E'Las gestoras de capital riesgo españolas han completado desinversiones por un importe agregado de más de 5.000 millones de euros, en términos de enterprise value, durante 2025, en un momento en que necesitan devolver capital a sus inversores para levantar nuevos fondos.\n\n## Principales operaciones por gestora\n\n### Portobello (+700M€)\n- **Vitalia** (10%): Vendido a StepStone y Greykite. Valoración: 900M€\n- **USA Group**: Traspasado a Stellum Capital por 150M€\n- **AGQ** (35%): Cedido a Fremman Capital. Valoración: ~300M€\n- **Mediterránea**: Vendido a Sodexo\n- **Serveo**: Fondo de continuación de 350M€\n\n### MCH (6 desinversiones)\n- **Fermax**: Vendido a Ardian por 220M€\n- **Avantia**: Traspasado a HIG. Valoración: ~330M€\n- **Altadia**: Cedido a Vayner por 100M€\n- **Litalsa**: MBO con CEO y Oquendo\n- **Vaughan**: Vendido a Tutore\n- **Brasmar**: Reducción de participación a Axyx\n\n### GPF (5 salidas)\n- **NOX**: Vendido a Oakley Capital. Valoración: 80-100M€\n- **Imedexa**: Traspasado a Sempag por 150M€\n- **Gestair**: Cedido a Azaga e Hyperion. Valoración: ~100M€\n- **Somos**: Adquirida por Joaquín Guell y Jaime Castellanos\n- **Vicam**: Vendido a Ontime\n\n### ProA Capital (4 ventas)\n- **Soltium**: Vendido a Koesio. Valoración: ~250M€\n- **Deflairut**: Traspasado a Andros por 150M€\n- **Avisa**: Cedido a Proponent. Valoración: ~100M€\n- **Patatas Hijolusa**: Fondo de continuación\n\n### Otras operaciones destacadas\n- **Tradeinn**: Suma Capital vende a Apollo por 1.000M€\n- **Bidasoa**: Inveready obtiene valoración de 640M€\n- **Samy Alliance**: Aurica vende a Bridgepoint\n- **Nuzoa**: Abac traspasa a PAI\n- **Alannia**: Corpfin vende a PAI\n\n## Tendencias del mercado\n\nLas operaciones han requerido plazos más largos y estructuras flexibles como earn-outs, roll-overs y vehículos híbridos. Las buenas perspectivas macroeconómicas de España hacen prever un 2026 positivo, con el mercado ibérico ganando atractivo frente a otras geografías europeas para fondos internacionales.',
  'Private Equity',
  ARRAY['capital riesgo', 'private equity', 'desinversiones', 'Portobello', 'MCH', 'GPF', 'ProA', 'fondos españoles', '2025'],
  'Expansión',
  'https://www.expansion.com/empresas/2026/01/10/capital-riesgo-espanol-ventas.html',
  '2026-01-10T00:00:00Z',
  true,
  true,
  'desinversión',
  'Apollo, Ardian, HIG, Oakley Capital, Bridgepoint, PAI, Koesio, Andros',
  'Portobello, MCH, GPF, ProA Capital, Suma Capital, Aurica, Abac, Corpfin',
  'Tradeinn, Fermax, Avantia, NOX, Soltium, Vitalia, AGQ, Imedexa',
  '+5.000M€ agregado',
  10,
  '{"total_deals": 20, "top_deal": "Tradeinn 1.000M€", "main_buyers": ["Apollo", "Ardian", "HIG", "Oakley Capital"], "main_sellers": ["Portobello", "MCH", "GPF", "ProA"], "year": 2025}'::jsonb,
  8,
  'Pepe Bravo'
);