
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { optimizedSupabase } from './optimizedClient';

// Use optimized singleton client
export const supabase = optimizedSupabase;
